/*** 

Run through the array of emails and get all their records. then isolate all the ones who have class1_attended whatever start with a ','. T
hen remove it and add a comma to the end. then post that whole array back to shsp

*/


var request = require("request-promise");
require('dotenv').config();

var data = ['mark@mobilelocker.com','creeves@omnienceevents.com','ana@boldentity.com','bobbyannevandervalk@nsc.nl','anthony.monte@sharpspring.com','grisel.duran@iprospect.com','stevel@marshall-fenn.com','jason@aspensignatureproperties.com','ryoung@credithuman.com','derek.myers@sharpspring.com','srachel@sjc.marketing','emily.dietz@causeinspiredmedia.com','bruce.jones@preshmarketingsolutions.com','chris@edgerunner.io','steve@kokuacreativegroup.com','nancy@kokuacreativegroup.com','j.hernandez@stirista.com','Lcatron@hillyard.com','lem@aspensignatureproperties.com','jacob@orangeballcreative.com','alyssa@bmgtrue.com','rubin.press@velaspan.com','john@schaefer-media.com','dan.fitzgerald@celltracktech.com','cachai@inlat.la','andrea@boldentity.com','tami@contentedmedia.net','kvolpe@gobigwheel.com','alex@optocreative.com','caio@optocreative.com','wanda@optocreative.com','aumiller@lehighminingandnavigation.com','brianna@tbg.agency','kristia@themarketingblender.com','carolyn@healthcaresuccess.com','lrapoport@harveyagency.com','joanna.bradley@ebethesda.org','sarah@tebww.com','rafaelm@andersonmmp.com','celine@themarketingblender.com','kylies@tebww.com','pdank@asginvestigations.com','kellyannevolpe@gmail.com','frederic.brosseau@akuting.com','ruben@inlat.la','Kate@inlat.la','juancamilo@inlat.la','bill.crider@ascendum.com','josh@mediafrenzyglobal.com','dacia@themarketingblender.com','nick@wsicyberdesign.com','celestereh@icloud.com','d.gruszczynska@avsystem.com','bobby@heatoncompanies.com','keren@themarketingblender.com','ksmola@butlertill.com','carter@brandtheorygroup.com','vjiminez@boldentity.com','cyree@bmgtrue.com','ANDREW.PALIOUNGAS@KOBEDIGITAL.COM','jon@leadersofevolution.com','kan@wsicitywebsolutions.com','jonathan@optocreative.com','Linda@IdentityCreative.com','manny@rockmyimage.com','joe@stepsmarketing.com','amy@crativpackaging.com','maryf@tsrmgroup.com','beth@eyesoreinc.com','teun.vandenacker@teamlewis.com','billy@syn-star.co.uk','Niklas.Jung@teamlewis.com','juan.feal@teamlewis.com','jess@tomorrow-ifa.co.uk','fleur.dam@teamlewis.com','janneke.devries@teamlewis.com','zorina@qs.digital','a.detweiler@thelightstreamgroup.com','noelle.conrad@teamlewis.com','jorge.alvarez@sharpspring.com','jhed.flores@teamlewis.com','mblair@blaircomm.us','AHuhn@quadmedical.com','ddavila@cbdmarketing.com','amcintire@vantagep.com','LMeade@convergomarketing.com','kaylee@thedesigngrouponline.com','analisa.quinn@teamlewis.com','afrasca@harveyagency.com','roger.kaiser@afc.org','bowens@morino.com','brooke.deason@waynereaves.com','marissa@communiteers.nl','KMarsh@convergomarketing.com','dan@pecchiacomm.com','dave@gokaizensales.com','phil.jones@inspire.world','greyson@moreprospectsnow.com','daniel.lappert@afc.org','amelia@thedesigngrouponline.com','ivonne.schmeling@teamlewis.com','jberkshire@morino.com','tyler.horne@waynereaves.com','Kelli@pecchiacomm.com','rui.pinto@teamlewis.com','ellis.taylor@teamlewis.com','federica.campori@teamlewis.com','yvonne.vanbokhoven@teamlewis.com','clara.ferreira@teamlewis.com','mariapia.bevilacqua@teamlewis.com','paul.english@refreshrenovations.com','anacristinaf@merxbp.com','esaukas@healthdiscourse.com','vic@venturearts.com','karine@sharpspring.com','hpellerin@vantagep.com','Sarah.carroll@netblaze.com','carolyn.leeper@gmail.com','branislav@redstardigitalmarketing.ca','zstratton@collateralcompanies.com','lee@obviouslee.com','disruptive@achievecmo.com','sarah.schacht@teamlewis.com','shannon@revup.com','izell.thurman@shawinc.com','brandon.hanson@sharpspring.com','christian@venturearts.com','cydney@disruptiveadvertising.com','mike@harriscmopartners.com','stivenfernandez@alacartema.com','Shane@vibmarketing.com','jochen@coemans.com','nicolo.ricciotti@bchannels.com','jadegarmo@thefrantzgroup.com','tim@disruptiveadvertising.com','ashleigh@harpethmarketing.com','mike.giambattista@gmail.com','jennifer@phixsolutions.com','mcarroll@carrollcommunications.net','Joshua.rubens@qs.digital','rachel@frankelmedia.com','tim@go-agency.com','hansela@traffic.net.nz','garethp@traffic.net.nz','Kelly.Bass@ascendum.com','carolinae@simantel.com','sarah@jumpsixmarketing.com','mae@schnapdigital.com','dorozco@gdlsystems.com','heath.laudick@ascendum.com','merinna@jumpsixmarketing.com','pat@qs.digital','Eva.vogt@safelinkhub.com','scottv@prosar.com','heather.vanlin@saagie.com','deontae.lafayette@sharpspring.com','david@deskboundtherapy.com','sturner@galapagosmarketing.com','ageorgieva@lcpgroup.com','dorinne.hoss@symbiontgroup.com','kasandra.still@linkupmedia.com','eric@apex-mbs.com','acheng@3vgeomatics.com','alex.silva@sharpspring.com','maxwell.davison@sharpspring.com','jason@apex-mbs.com','YScott-Younis@mohawkglobal.com','amelia.hernandez@opinno.com','gdisalvo@cssienroll.com','ecriswell@balzac.com','ken@oktane.net','kmccaw@leelanau.org','gpineiro@riester.com','sstern@magnifygood.com','Uday.Kumar@ascendum.com','cschwartzly@eastcoastmetrology.com','skyler@localimpactgroup.com','ashley@localimpactgroup.com','bg@localimpactgroup.com','KCerrillo@expandable.com','alec@aenow.com','Kdebias@leaddogms.com','joressie@teamfomco.com','michelle@theindustriouscompany.com','brittney.thompson@sharpspring.com','Ashley@wholewheatcreative.com','sdelasllagas@expandable.com','gbarnes@hargerhowe.com','kathleen@advancementcommunications.com','katie@aenow.com','jeff@superboltstudios.com','january.moore@bbim.com','walter.winn@sharpspring.com','woody@innovationsimple.com','sean.redmond@sharpspring.com','marketing@sachalodge.com','sanshiro@alohacreativos.com','sina@sistaraden.se','emily@rootscreative.co.uk','sri@sourcebits.com','todd@tempcon.net','jef.liekens@sbb.be','Suresh.R@ascendum.com','rbarnett@emaginereality.com','nelson@fullsail.media','johnson@lehighminingandnavigation.com','bill@egintegrated.com','amy.bielecki@enternest.com','leonardmichaellee@gmail.com','aherold@koeppeldirect.com','info@jaxoncommunications.com','elyse@fuelfx.com','scottbizproconsulting@gmail.com','Annie@talkoutloud.biz','othniel.ashidam@sharpspring.com','mike@maxlead.com','jason@metamorf.net','tbyrne@revenuearchitects.com','jessica@aletheiadigital.com','santiago@metamorf.net','cheryl@gosimc.com','mjavier@wslstrategicretail.com','harrynorman@wearemerci.com','chris@interval.marketing','chad.erpelding@inspire.world','sthomas@safewareinc.com','janel.wilkerson@bbim.com','riley.otoole@bbim.com','Ray@7bridgesmarketing.com','samantha.aiken@bbim.com','tracey.noe@bbim.com','craig@7bridgesmarketing.com','ssarbacher@safewareinc.com','sarah.ludwig@sharpspring.com','craig@pivotmode.com','kelly@convinceandconvert.com','seth.graham@bbim.com','tucker.carper@bbim.com','lisa.eldridge@powersmiths.com','brandon.johnson@bbim.com','michael.leonard@bbim.com','ryan@eosworldwide.com','joy@smalldogcreative.com','bkrueger@themusiccircus.org','wayne.thurman@bbim.com','aaron.perkins@bbim.com','stephanie.harrison@sharpspring.com','Owen.shapiro@icloud.com','jmcg@alphaimpact.marketing','azippin@firsttracksmarketing.com','nikki@safeshops.be','larahavord@wearemerci.com','justin@imedmobility.com','megan@convinceandconvert.com','rick.ford@bbim.com','mmcdonald@destaco.com','kristen.parker@bbim.com','petewebb@wearemerci.com','eva.vogt@safelink.cloud','ashleigh@spraycancreative.com','andres@simpleoptimization.com','ty@acdc.io','Gavin@ihm.co.uk','steve.bissett@xposurecreative.co.uk','lucienw@gmail.com','katrina.mcafee@sharpspring.com','fbarbosa@voznia.mx','lisaa@colorworksinc.com','jim@kiefferconsulting.com','lucien.wegner@gmail.com','larryoconnors@gmail.com','annis@sistaraden.se','sshaw@arminsight.com','droche@lake34.com','matt@edgemm.com','sheree@lake34.com','sharr@alphaimpact.marketing','jmarkle@m1cu.org','jason@cultivize.com','davis.ortiz@godigital.pe','ivan.gonzales@godigital.pe','sylvia@simpleisgood.ca','paul@coalescemarketing.com','adam@mailingmanager.co.uk','jb@ihm.co.uk','stellan@sistaraden.se','garrett@rejuvmedical.com','keith@ignite-revenue.com','jackr@canna-ventures.com','zberger@cerconebrown.com','gino@crossfitbrave.com','andrew@ninjavision.com','kvanblerk@dvt.co.uk','alex@mailingmanager.co.uk','ryan@ryanwinterllc.com','jsambol@labeltronix.com','matt@damangmedia.com','andrea.morassutti@mediaprofile.com','TimSatterfield@ptpmarketing.com','evin.lachance@mediaprofile.com','lnaidoo@dvt.co.za','ahawtonhill@gmail.com','jennifer@quinn.agency','irina.javaheri@sharpspring.com','alan@jubilantdigital.com','susan@ptpmarketing.com','lindsey@partnerinpublishing.com','catherine.ringeisen@5fold.agency','pcsoucie@gmail.com','mmccormick@thumbies.com','bjacobs@magnifygood.com','smitty@sharpspring.com','george@affordabletours.com','phil@befamousmedia.com','richard@zen.agency','cvisser@dvt.co.za','nick@thepodadvertising.com','Margaret.Crowson@Halliburton.com','ewing@metrocreate.com','ahmed@funnelbud.com','bstiller@metrocreate.com','tim@ptpmarketing.com','Andressa.Toni@Halliburton.com','debbi@rosenbaumfinancial.com','juan.lv@3zero.mx','stephanie@nascentcorp.io','miranda.buesing@arvigmedia.com','srichards@selkirk.ca','khildebrand@selkirk.ca','iamterickson@gmail.com','andrew.rennie@keysolarsolutions.com','kalyea@aapg.org','Zach@digimar.com','candela@pinchaaqui.es','pskaper@kinetixmedia.com','charly.baune@arvigmedia.com','morgan@evercommerce.com','Rich.weymer@gmail.com','jmoss@twoxfour.com','lschevers@sanbio.nl','derek@nascentcorp.io','stephanie.quinn@welchallyn.com','mark.ivy@gsm.marketing','christine@ctgnow.com','wes@hdteks.com','yarl.thomas@ultrimaxcoatings.co.uk','ashley.ohl@netblaze.com','web@orthopreneur.com','gaylehagler@trig.com','tara.smits@pacon.com','peter@cogito-wealth.co.uk','smitty+test@sharpspring.com','laura@publicadagency.com','cmcferrin@convergencepointmedia.com','bob.schnyder@ecd.com','leya.wood@sharpspring.com','cantrall@wrcresearch.com','chris.oconnor@firstcutmarketing.com','kooch43@aol.com','matthew.collins@sharpspring.com','aroijackers@sanbio.nl','wendy@cogito-wealth.co.uk','angel.ishmael@netblaze.com','mario@healthcare-compliance-inc.com','joe@brandx1.com','kguertin@expertservices.com','tstark@selkirk.ca','jack@aletheiadigital.com','kkochi@intellectfaces.com','jerelyn@shipstarter.com','joseph@shipstarter.com','Lyza@shipstarter.com','lgross@braunintertec.com','jrudolph@aapg.org','chise@aapg.org','gsmith@aapg.org','gflint@aapg.org','angel.netblaze@gmail.com','aaron@creatingresults.com','jessica.pimental@hill-rom.com','larry.oconnors@netblaze.com','valerie.lock@studio27.us','christopher.schaeffer@sharpspring.com','sreimer@newgroundco.com','jyablonsky@newgroundco.com','jchilson@newgroundco.com','lizziesnellings@gmail.com','zach@bigvoodoo.com','brandon.darling@sharpspring.com','ryan.loiacono@ccpdigital.com','alejandra.poblete.hdz@gmail.com','MSheeler@dacgroup.com','julianne@d3corp.com','virtualclassroom@sharpspring.com','dank@lotus823.com','Jenn@canddadvertising.com','amelias@figbytes.com','regan@contigocreative.com','colin.viti@apollollc.org','Daniel@syn-star.co.uk','ed@brandx1.com','claire@aletheiadigital.com','ashiq@leadcertain.com','jayquipa@smartboxtv.com','oalvarez@target-ddi.cl','federico.anedda@bchannels.com','mark@tamimiinvestments.com','mchen@dacgroup.com','lucy.nguyen@bmp-group.com','bwatters@aliaswire.com','andrewdimeo@trig.com','mjohnson@evercommerce.com','cory.hartlen@sharpspring.com','melany@dticreative.com','emurray@braunintertec.com','clampkin@plexusmarketing.com','paromita.sinha@kairospulse.com','tposey@aapg.org','niki@xivic.com','Marie.miller@dealerspike.com','emma@4salebydentist.com','AshleyWhitley@trig.com','Sue.Moore@amk-group.com','jnewlin@riester.com','samanthaharr@trig.com','StephenLindamood@trig.com','Everett.Miner@altana.com','mqueiroz@efemkt.com','carrie@canddadvertising.com','jdebbins@garrettleather.com','rachel.bolger@culturetrax.com','npalma@deliverycircle.com','jmuenzer@interdev.com','david@uniondisability.com','jescobar@target-ddi.cl','alma@slata.co','sarahm@adionsystems.com','james.martin@elucidata.io','karine.hervy@sharpspring.com','cmcbride@madewithmerit.com','Katie@cohlab.com','scott.fulton@culturetrax.com','rmcgrew@landmarkcpas.com','Stephan@hellodialog.com','vma@pivott.be','Jennifer.Greneaux@Halliburton.com','amber@webmarketsonline.com','luke@muddywatersmarketing.com','katarina.book@theextendgroup.com','Logan@cohlab.com','Kelsey@cohlab.com','TStuder@curiosity360.com','nschillero@illumetek.com','ghilson@supraits.com','sweng@rivetlogic.com','ccurry@gandlscientific.com','jheintz@hawkpt.com','don3@evolve-systems.com','sblessman@augustash.com','paul.anthony@ascendum.com','y.overkamp@gmu.online','jp@wespeakeasy.com','ablackburn@wespeakeasy.com','cole@leadoptimize.com','theo@leadoptimize.com','jlatta@newgroundco.com','kris@aimisresults.com','evan@epicfinancialconsulting.com','diogo.chaves@latigid.pt','Annie@xponent21.com','aroe@hospitalitymints.com','lgross@wh-m.com','jessica.amidon@welchallyn.com','mathieu.lecoeuche@bchannels.com','Matthew@sahlcomm.com','will.frank@ccpdigital.com','laura@ajhcreate.com','victoria.echeverria@culturetrax.com','noepetel@gmail.com','keegan@boltgoodly.com','elisa@fullsail.media','greg@mankomarketing.com','awells@directoptions.com','alex@contigocreative.com','dhankel@cimmp.com','cory.hartlen@procedureflow.com','amanda.verner@procedureflow.com','jbaker@asahi-america.com','josh@satellitesix.com','esydor@dbamar.com','devin@marketvantage.com','bettycontreras@nexycon.com.mx','megan@bigvoodoo.com','ryan.haarlemmer@tachyons.nl','stevefer01@gmail.com','jodie.hughes@ultrimaxcoatings.co.uk','kminerd@bene-care.com','becky@surgemarketingstudio.com','brock@cleanlinetasman.co.nz','peter@aimisresults.com','phamilton@crmdirectplus.com','mary.brown@servicewire.com','Peter@readyartwork.com','erin@d3corp.com','lfrench@wh-m.com','marty@starfishco.com','Heather@cohlab.com','jon@consult-mc.com','deon@inspiredmarketing.co.za','garrett@werremeyer.com','kroczek.alina@gmail.com','edwards_clara@yahoo.com','Deanna.fisher@gsm.marketing','louise@kayacontent.com','kerry@inspiredmarketing.co.za','monica@nexycon.com.mx','shelly@marburycreativegroup.com','elsy.aelvoet@bluematters.be','emilia@beholderproductions.com','brandon@kitestring.ca','jenn@kitestring.ca','Melissa.collins@theextendgroup.com','rbolz@holland-mark.com','shawn.collins@theextendgroup.com','chris@leadoptimize.com','hollie@netaffinity.com','mmcclellan@plexusmarketing.com','scott@liquidcreativestudio.com','eve@ashworthcreative.com'];

var realData = [{emailAddress:'kellyannevolpe@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4, Class 5'},
{emailAddress:'ruben@inlat.la',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'greyson@moreprospectsnow.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2'},
{emailAddress:'lrapoport@harveyagency.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'noelle.conrad@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'Shane@vibmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'janneke.devries@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'rui.pinto@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'celestereh@icloud.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'izell.thurman@shawinc.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'heath.laudick@ascendum.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'rachel@frankelmedia.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'afrasca@harveyagency.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'beth@eyesoreinc.com',
class_1_attended_5c4093bbcf4ab: 'Class 3,Class 4'},
{emailAddress:'bruce.jones@preshmarketingsolutions.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'Joshua.rubens@qs.digital',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'lem@aspensignatureproperties.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5'},
{emailAddress:'kan@wsicitywebsolutions.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5'},
{emailAddress:'carter@brandtheorygroup.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'bill.crider@ascendum.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'kylies@tebww.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'billy@syn-star.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'Sarah.carroll@netblaze.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 5'},
{emailAddress:'frederic.brosseau@akuting.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'branislav@redstardigitalmarketing.ca',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 5'},
{emailAddress:'alex.silva@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'vic@venturearts.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'Linda@IdentityCreative.com',
class_1_attended_5c4093bbcf4ab: 'Class 4'},
{emailAddress:'seth.graham@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4'},
{emailAddress:'marissa@communiteers.nl',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4'},
{emailAddress:'juancamilo@inlat.la',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'pdank@asginvestigations.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'bill@egintegrated.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'carolinae@simantel.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'brooke.deason@waynereaves.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4'},
{emailAddress:'ddavila@cbdmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 5'},
{emailAddress:'info@jaxoncommunications.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'steve.bissett@xposurecreative.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 5'},
{emailAddress:'hpellerin@vantagep.com',
class_1_attended_5c4093bbcf4ab: ',Class 1,Class 2,Class 3,Class 4,Class 5, Class 3, Class 5'},
{emailAddress:'Lcatron@hillyard.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'acheng@3vgeomatics.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'chris@edgerunner.io',
class_1_attended_5c4093bbcf4ab: 'Class 1'},
{emailAddress:'derek.myers@sharpspring.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4'},
{emailAddress:'Kelly.Bass@ascendum.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'elyse@fuelfx.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'Niklas.Jung@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'KMarsh@convergomarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'tucker.carper@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'cheryl@gosimc.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'jacob@orangeballcreative.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'bobby@heatoncompanies.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'eva.vogt@safelink.cloud',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'scottv@prosar.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'jberkshire@morino.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'a.detweiler@thelightstreamgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 2'},
{emailAddress:'dacia@themarketingblender.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'sri@sourcebits.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'brandon.johnson@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'harrynorman@wearemerci.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4'},
{emailAddress:'joy@smalldogcreative.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4'},
{emailAddress:'steve@kokuacreativegroup.com',
class_1_attended_5c4093bbcf4ab: ',Class 5, Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'clara.ferreira@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'brittney.thompson@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'amelia.hernandez@opinno.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'AHuhn@quadmedical.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'garethp@traffic.net.nz',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'mmcdonald@destaco.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'ksmola@butlertill.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4, Class 3'},
{emailAddress:'Kelli@pecchiacomm.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'anthony.monte@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ',Class 4, Class 2, Class 3, Class 4'},
{emailAddress:'rick.ford@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4'},
{emailAddress:'daniel.lappert@afc.org',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'mblair@blaircomm.us',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'joe@stepsmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 5, Class 2'},
{emailAddress:'jason@aspensignatureproperties.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'dave@gokaizensales.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'sarah.ludwig@sharpspring.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4'},
{emailAddress:'leonardmichaellee@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'dan.fitzgerald@celltracktech.com',
class_1_attended_5c4093bbcf4ab: ',Class 5, Class 2, Class 1, Class 3'},
{emailAddress:'santiago@metamorf.net',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4, Class 5'},
{emailAddress:'mike.giambattista@gmail.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'josh@mediafrenzyglobal.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'rbarnett@emaginereality.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'othniel.ashidam@sharpspring.com',
class_1_attended_5c4093bbcf4ab: 'Class 3'},
{emailAddress:'petewebb@wearemerci.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4'},
{emailAddress:'zstratton@collateralcompanies.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 5'},
{emailAddress:'hansela@traffic.net.nz',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'lucienw@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'janel.wilkerson@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'woody@innovationsimple.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 5'},
{emailAddress:'january.moore@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'megan@convinceandconvert.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'alec@aenow.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4, Class 5'},
{emailAddress:'riley.otoole@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'stellan@sistaraden.se',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'anacristinaf@merxbp.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5'},
{emailAddress:'YScott-Younis@mohawkglobal.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'joanna.bradley@ebethesda.org',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'Ashley@wholewheatcreative.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'aherold@koeppeldirect.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'kelly@convinceandconvert.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'Kdebias@leaddogms.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4, Class 5, Class 1'},
{emailAddress:'droche@lake34.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'ivan.gonzales@godigital.pe',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'sean.redmond@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'ssarbacher@safewareinc.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 4'},
{emailAddress:'jmarkle@m1cu.org',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'alex@mailingmanager.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'bstiller@metrocreate.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'gdisalvo@cssienroll.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 5'},
{emailAddress:'wayne.thurman@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'aumiller@lehighminingandnavigation.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'karine@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'bkrueger@themusiccircus.org',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'matt@edgemm.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'chad.erpelding@inspire.world',
class_1_attended_5c4093bbcf4ab: ', Class 2'},
{emailAddress:'miranda.buesing@arvigmedia.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'ryan@eosworldwide.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'christian@venturearts.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'bg@localimpactgroup.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'eric@apex-mbs.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'Suresh.R@ascendum.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'kvanblerk@dvt.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'fleur.dam@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'jennifer@phixsolutions.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'ivonne.schmeling@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'jhed.flores@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'azippin@firsttracksmarketing.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'juan.feal@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'ANDREW.PALIOUNGAS@KOBEDIGITAL.COM',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 4,Class 5'},
{emailAddress:'jorge.alvarez@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'christine@ctgnow.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'larahavord@wearemerci.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'mcarroll@carrollcommunications.net',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'Annie@talkoutloud.biz',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'ashleigh@harpethmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4, Class 5'},
{emailAddress:'amelia@thedesigngrouponline.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'andrea@boldentity.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4, Class 5'},
{emailAddress:'tim@disruptiveadvertising.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'mike@maxlead.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4'},
{emailAddress:'gaylehagler@trig.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'amcintire@vantagep.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'carolyn.leeper@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 2'},
{emailAddress:'jess@tomorrow-ifa.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'federica.campori@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'manny@rockmyimage.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'kaylee@thedesigngrouponline.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'jochen@coemans.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'ana@boldentity.com',
class_1_attended_5c4093bbcf4ab: 'Class 2,Class 3'},
{emailAddress:'nick@thepodadvertising.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'scottbizproconsulting@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 5'},
{emailAddress:'jsambol@labeltronix.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'lucien.wegner@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 2'},
{emailAddress:'yvonne.vanbokhoven@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3'},
{emailAddress:'sarah@jumpsixmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 1, Class 3, Class 5'},
{emailAddress:'george@affordabletours.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5, Class 3'},
{emailAddress:'d.gruszczynska@avsystem.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'cyree@bmgtrue.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'zorina@qs.digital',
class_1_attended_5c4093bbcf4ab: ',Class 5, Class 2, Class 1, Class 3, Class 4'},
{emailAddress:'Ray@7bridgesmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'skyler@localimpactgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4'},
{emailAddress:'Gavin@ihm.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 5'},
{emailAddress:'jef.liekens@sbb.be',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4'},
{emailAddress:'paul.english@refreshrenovations.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'ashleigh@spraycancreative.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'ellis.taylor@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'maryf@tsrmgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4'},
{emailAddress:'Kate@inlat.la',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'LMeade@convergomarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'lisa.eldridge@powersmiths.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4'},
{emailAddress:'sthomas@safewareinc.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'sheree@lake34.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3, Class 4, Class 5'},
{emailAddress:'pskaper@kinetixmedia.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'aroijackers@sanbio.nl',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'lisaa@colorworksinc.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'nick@wsicyberdesign.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 4,Class 5'},
{emailAddress:'gpineiro@riester.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'kvolpe@gobigwheel.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'ty@acdc.io',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'smitty+test@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'jon@leadersofevolution.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'sshaw@arminsight.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'katrina.mcafee@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ',Class 4'},
{emailAddress:'justin@imedmobility.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'kguertin@expertservices.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'michelle@theindustriouscompany.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'sdelasllagas@expandable.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'sreimer@newgroundco.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'ewing@metrocreate.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'jmcg@alphaimpact.marketing',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 3'},
{emailAddress:'samantha.aiken@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'gbarnes@hargerhowe.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'caio@optocreative.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'cydney@disruptiveadvertising.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3'},
{emailAddress:'amy@crativpackaging.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'teun.vandenacker@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'Kelsey@cohlab.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4'},
{emailAddress:'mqueiroz@efemkt.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4, Class 5'},
{emailAddress:'chise@aapg.org',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3'},
{emailAddress:'mjavier@wslstrategicretail.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'nelson@fullsail.media',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'joe@brandx1.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'samanthaharr@trig.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'zach@bigvoodoo.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'stevel@marshall-fenn.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'michael.leonard@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'alejandra.poblete.hdz@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'mmccormick@thumbies.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 5'},
{emailAddress:'jonathan@optocreative.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 1, Class 2'},
{emailAddress:'nancy@kokuacreativegroup.com',
class_1_attended_5c4093bbcf4ab: ',Class 5, Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'davis.ortiz@godigital.pe',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 5'},
{emailAddress:'esydor@dbamar.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5'},
{emailAddress:'dorinne.hoss@symbiontgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'sina@sistaraden.se',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'keegan@boltgoodly.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'ecriswell@balzac.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'todd@tempcon.net',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'ahmed@funnelbud.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'wendy@cogito-wealth.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4'},
{emailAddress:'emily.dietz@causeinspiredmedia.com',
class_1_attended_5c4093bbcf4ab: ',Class 4, Class 1, Class 2, Class 3'},
{emailAddress:'peter@aimisresults.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4, Class 5'},
{emailAddress:'dhankel@cimmp.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 5'},
{emailAddress:'cory.hartlen@procedureflow.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'ashiq@leadcertain.com',
class_1_attended_5c4093bbcf4ab: ', Class 5'},
{emailAddress:'karine.hervy@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'jim@kiefferconsulting.com',
class_1_attended_5c4093bbcf4ab: 'Class 3,Class 4,Class 5'},
{emailAddress:'joressie@teamfomco.com',
class_1_attended_5c4093bbcf4ab: ',Class 1, Class 2'},
{emailAddress:'analisa.quinn@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'richard@zen.agency',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 3'},
{emailAddress:'virtualclassroom@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ',Class 5,Class 4, Class 5, Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'craig@7bridgesmarketing.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'pat@qs.digital',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'jescobar@target-ddi.cl',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'amber@webmarketsonline.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 5'},
{emailAddress:'sstern@magnifygood.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'cachai@inlat.la',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'gino@crossfitbrave.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'alex@contigocreative.com',
class_1_attended_5c4093bbcf4ab: ', Class 3'},
{emailAddress:'brandon.hanson@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'phil.jones@inspire.world',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'vjiminez@boldentity.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'Rich.weymer@gmail.com',
class_1_attended_5c4093bbcf4ab: ', Class 4'},
{emailAddress:'derek@nascentcorp.io',
class_1_attended_5c4093bbcf4ab: 'Class 2'},
{emailAddress:'disruptive@achievecmo.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'Owen.shapiro@icloud.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'zberger@cerconebrown.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 5'},
{emailAddress:'dorozco@gdlsystems.com',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5'},
{emailAddress:'roger.kaiser@afc.org',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'keren@themarketingblender.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'tyler.horne@waynereaves.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'oalvarez@target-ddi.cl',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'esaukas@healthdiscourse.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 1'},
{emailAddress:'marketing@sachalodge.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'lucy.nguyen@bmp-group.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 4'},
{emailAddress:'jadegarmo@thefrantzgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'katie@aenow.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'mike@harriscmopartners.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'kooch43@aol.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'j.hernandez@stirista.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'celine@themarketingblender.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4'},
{emailAddress:'Zach@digimar.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'melany@dticreative.com',
class_1_attended_5c4093bbcf4ab: ''},
{emailAddress:'tim@go-agency.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'heather.vanlin@saagie.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'jessica@aletheiadigital.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'stephanie.quinn@welchallyn.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'susan@ptpmarketing.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'sanshiro@alohacreativos.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'jeff@superboltstudios.com',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2'},
{emailAddress:'Everett.Miner@altana.com',
class_1_attended_5c4093bbcf4ab: ',Class 4, Class 5, Class 1, Class 2'},
{emailAddress:'charly.baune@arvigmedia.com',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'lee@obviouslee.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'irina.javaheri@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2'},
{emailAddress:'mark@mobilelocker.com',
class_1_attended_5c4093bbcf4ab: 'Class 4'},
{emailAddress:'grisel.duran@iprospect.com',
class_1_attended_5c4093bbcf4ab: ',Class 4,Class 3'},
{emailAddress:'rafaelm@andersonmmp.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 4, Class 5'},
{emailAddress:'john@schaefer-media.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'stephanie.harrison@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 4, Class 5'},
{emailAddress:'alma@slata.co',
class_1_attended_5c4093bbcf4ab: ', Class 4, Class 5, Class 2, Class 3, Class 1'},
{emailAddress:'andrewdimeo@trig.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'annis@sistaraden.se',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3'},
{emailAddress:'ashley@localimpactgroup.com',
class_1_attended_5c4093bbcf4ab: ', Class 3, Class 4, Class 5'},
{emailAddress:'tracey.noe@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'craig@pivotmode.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3'},
{emailAddress:'dank@lotus823.com',
class_1_attended_5c4093bbcf4ab: ',Class 4, Class 1, Class 2'},
{emailAddress:'mariapia.bevilacqua@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'aaron.perkins@bbim.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'maxwell.davison@sharpspring.com',
class_1_attended_5c4093bbcf4ab: ', Class 1'},
{emailAddress:'johnson@lehighminingandnavigation.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'jason@metamorf.net',
class_1_attended_5c4093bbcf4ab: ', Class 2, Class 3, Class 5'},
{emailAddress:'sarah.schacht@teamlewis.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4'},
{emailAddress:'adam@mailingmanager.co.uk',
class_1_attended_5c4093bbcf4ab: 'Class 1,Class 2,Class 3,Class 4,Class 5'},
{emailAddress:'jb@ihm.co.uk',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'},
{emailAddress:'kminerd@bene-care.com',
class_1_attended_5c4093bbcf4ab: ',Class 4, Class 5, Class 1, Class 2'},
{emailAddress:'awells@directoptions.com',
class_1_attended_5c4093bbcf4ab: ', Class 1, Class 2, Class 3, Class 4, Class 5'}]

const getLead = async (email) => {
  var options = { method: 'POST',
  url: 'https://api.sharpspring.com/pubapi/v1/',
  qs: 
   { accountID: process.env.AccID,
     secretKey: process.env.SecKey },
  headers: 
   { 'cache-control': 'no-cache',
     'Content-Type': 'application/json' },
  body: 
   { method: 'getLeads',
     params: { where: { emailAddress: email } },
     id: `${Math.floor(Math.random*10000)}` },
  json: true };

  var lead = await request(options);
  return lead.result.lead[0];

}

const postLeadsToSharpSpring = async (leads) => { 
  //Prep leads with formatting
  var preformattedLeads = await prepareLeadRecords(leads);
  var allLeads = formatForPost(preformattedLeads);

  var newLeadReponse = "No new leads", updateLeadResponse = "No leads to update.";
  
  if (allLeads.newLeads.length>0){
    // [Start postLeads]
    // -- Post leads, new and updates, to ShSp.
    // -- Handle connection errors and leads not existing
    newLeadReponse = await postLeads(allLeads.newLeads, "createLeads"); }
  if (allLeads.updateLeads.length>0){
    updateLeadResponse = await postLeads(allLeads.updateLeads, "updateLeads"); }
  // [End postLeads]
  return {newLeadReponse: newLeadReponse, 
          updateLeadResponse: updateLeadResponse}
  
}

const formatForPost = (participants) => {
  var newLeads = participants.filter((lead) => {
    if (lead.method.includes("createLeads")) {return JSON.stringify(lead);}
  });

  var updateLeads = participants.filter((lead) => {
    if (lead.method.includes("updateLeads")) {return /*JSON.stringify*/(lead);}
  })

  var newLeadsArray = newLeads.map((lead) => {
    return lead.person;
  })

  var updateLeadsArray = updateLeads.map((lead) => {
    return (lead.person);
  })

return {newLeads: (newLeadsArray),
        updateLeads: (updateLeadsArray)}
}

const postLeads = async (leads, method) => {
  
  var options = { method: 'POST',
  url: 'https://api.sharpspring.com/pubapi/v1/',
  qs: 
   { accountID: process.env.AccID,
     secretKey: process.env.SecKey },
  headers: 
   { 'cache-control': 'no-cache',
     'Content-Type': 'application/json' },
  body: 
   { method: method,
     params: {
       objects: leads,
      },
     id: "1001" },
  json: true };
try {
  var lead = await request(options);
  return lead;
} catch (err) {return err}
  
}

const prepareLeadRecords = async (_leads) => {
  var preparedLeads = await Promise.all([_leads].map(async(person) => {
    var data;
    var lead = await getLead(person.emailAddress);
    if (lead) {
      data = {
          person,
          method: "updateLeads"
      }
    }
    // If lead doesn't yet exist in ShSp
    else {
      person.leadStatus= "contact";
      data = {
        person,
        method: "createLeads"
      }
    }
    return data   
    }))
  return preparedLeads;
}

const displayResults = (result) => {
  console.log(`New Lead Response: ${JSON.stringify(result.newLeadReponse)}\nUpdated Lead Response: ${JSON.stringify(result.updateLeadResponse)}`);
}

const removeTrainingComma = async (data) => {
  console.log("starting");

  var promises = data.map(async email =>  {
    var person = await getLead(email);
    console.log(`{emailAddress:'${person.emailAddress}',\nclass_1_attended_5c4093bbcf4ab: '${person.class_1_attended_5c4093bbcf4ab}'},`)
    //return {emailAddress: person.emailAddress,class_1_attended_5c4093bbcf4ab: person.class_1_attended_5c4093bbcf4ab };
  })

  var results = await Promise.all(promises);
  console.log(results);
      //var result = await postLeadsToSharpSpring(lead);
     // displayResults(result);
        
  } 

const removeComma = async (data) => {
  var preppedData = data.map(lead => {
    if (lead.class_1_attended_5c4093bbcf4ab.charAt(0)==",") {
      return {
        emailAddress: lead.emailAddress,
        class_1_attended_5c4093bbcf4ab: `${lead.class_1_attended_5c4093bbcf4ab.slice(2)},`
      }}
      else return lead;
    }
  )
  var results = await postLeadsToSharpSpring(preppedData);
}  

  //removeTrainingComma(data);
  removeComma(realData);
